name: Atualizar GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v6

      - name: Gerar estatísticas do GitHub
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=danilyyl&show_icons=true&include_all_commits=true&theme=dracula
          path: github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gerar linguagens mais utilizadas
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=danilyyl&layout=compact&langs_count=5&theme=dracula
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Salvar estatísticas
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg top-langs.svg
          git diff --cached --quiet || git commit -m "Atualizar GitHub Stats [skip ci]"
          git push
